name: Deploy to Develop

on:
  workflow_run:
    workflows: ['Continuous Integration'] # Triggers after the specified workflow completes
    types:
      - completed

jobs:
  deploy:
    name: Deploy to Develop
    environment:
      name: develop
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.conclusion == 'success' &&  
      contains(github.event.workflow_run.head_branch, 'develop')

    steps:
      - name: Trigger AWS CodePipeline
        run:
          aws codepipeline start-pipeline-execution --name ${{
          vars.CODE_BUILD_PIPELINE }} --region ${{ vars.AWS_REGION }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
